kind: database
paths:
  - backend/app/models
  - backend/scripts
file_patterns:
  - "**/*.py"
  - "**/*.sql"
semantics:
  relationships: one-to-many, many-to-many
  migrations: scripts
  queries: orm/raw
priority:
  - models
  - migrations
  - queries